### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by redDwarf03** [WalletConnect/Web3ModalFlutter#108]
Hello @quetool 

i'm trying to help you to support Flutter Web.

First, i've updated `WalletConnectFlutterV2`project:
Work was well underway. The only change was to give priority to the `kIsWeb` control to prevent the `Platform` conditions from crashing in web mode.
See: https://github.com/redDwarf03/WalletConnectFlutterV2/commit/cc39bcfb850e163760c704c3f2541bd473a42eac

After that, i've updated `Web3ModalFlutter`project with the same updates like `WalletConnectFlutterV2` about the order of the controls (`kIsWeb`first)
See: https://github.com/redDwarf03/Web3ModalFlutter/commit/19830a182cad75694ccbd3011cb6029f922aefef

My current issue is about this message.
I think perhaps `api.web3modal` doesn't accept `platform=platformtype.web`.

Could you help me or confirm it to try go continue to test and update the lib to support web platform.

```
apiUrl https://api.web3modal.com
headers {x-project-id: ce9ee3c8e58873e8708247895990bc27, x-sdk-type: w3m, x-sdk-version: flutter-3.2.0-beta04, user-agent: w3m-flutter-3.2.0-beta04/flutter_2.2.2/web-browser, referer: Web3ModalFlutterExample}
uri https://api.web3modal.com/getWallets?page=1&entries=48&platform=platformtype.web
response Instance of 'Response'
response body Bad Request
Error: Exception: 2.718281828459045
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
packages/web3modal_flutter/services/explorer_service/explorer_service.dart 291:3  _fetchListings
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
```

Thx!

**Comment by redDwarf03** [comment]
i will push PR when tests are ok or perhaps you prefer to have a PR now. Tell me

**Comment by quetool** [comment]
Hello @redDwarf03! This is awesome, thanks, I'll take a look at WalletConnectFlutterV2 PR ASAP but just for you to know I have a PR for web support ready to be merged https://github.com/WalletConnect/WalletConnectFlutterV2/pull/281
I just couldn't do it yet.

Regarding your `api.web3modal` inquiry, indeed `platformtype.web` is not supported, in case of web you just don't send platform

**Comment by redDwarf03** [comment]
i commit WalletConnectFlutterV2 project from your web_support branch for info

**Comment by redDwarf03** [comment]
can we exchange on discord or TG to facilitate the exchange or we exchange here?

**Comment by quetool** [comment]
Let's do it here, please, we like to be open by default. In any case I was planning to work on Web3Modal web support soon, so maybe you want to wait my PR and review it? As you please

**Comment by redDwarf03** [comment]
i can review it.
Just for info too, i'm not sure to understand your issue with tests by when i launch `flutter test`on `WalletConnectFlutterV2`project, i have `+225: All tests passed!   `

**Comment by quetool** [comment]
Oh yeah, I thought you were talking about Web3Modal tests. Sorry my confusion. Yes, WalletConnectFlutterV2 tests are fine.

> i confess i would like to have it soon.. that's for it i'm trying to help you.
It's a priority for us but it's not going to be easy. We have a few dependencies on Web3Modal that are not supported on Web (like CoinbaseWalletSDK and some other more) and conditional importing these will be tricky. I honestly don't know the exact lift on this but the more I think of it the more I realize we will end up having a lightweight version of Web3Modal on web. 

Also, if all you need for now is simply stuff you could try support web on https://github.com/WalletConnect/WalletConnectModalFlutter. This is a lightweight modal from us

**Comment by gvbinarybard** [comment]
@quetool  @redDwarf03 - I am using the  [WalletConnectModalFlutter] (https://github.com/WalletConnect/WalletConnectModalFlutter and so far it works well with the web , it just you need to some changes for  redirecting the app to wallet in  for the mobile browser 
Also the network change is not reliable but it is nothing to do the walletconnect but there is some issue with the Metamask 
@redDwarf03  -let me know if you need any help on this

**Comment by gvbinarybard** [comment]
@kaumudpa  -  Sure 

In a Flutter PWA, when attempting to connect to a wallet using the `connectWallet` method, the app fails to navigate or deep link to the selected wallet. This issue arises due to limitations in Safari and Chrome browsers, where redirection to another app is not permitted following an asynchronous task. To overcome this obstacle, I have developed a workaround that involves creating a separate page. This page is displayed after successfully invoking the `rebuildConnectionUri()` method and redirecting the application  to the desired wallet

**Regarding your issue**, yes  even I  faced the same issue and you can fix it by adding extra  && condition `!kIsWeb` in url_utils.dart file line no 99 
`if (nativeUri != null && !kIsWeb) {`

Let me know if this helps

**Comment by kaumudpa** [comment]
@gvbinarybard 

Your solution for `if (nativeUri != null && !kIsWeb) {` works perfectly - I am still confused with the PWA workaround - Can you share some code here? Tried implementing it but may be i am missing someting as i end up without luck.

**Comment by gvbinarybard** [comment]
@kaumudpa  - `if (nativeUri != null && !kIsWeb)`  is the only change required for redirecting back to the app 
I am a bit confused , is it working for you or not as you said  works perfectly but later you are saying  as i end up without luck.

**Comment by kaumudpa** [comment]
@gvbinarybard Redirecting works perfectly from the browser on mobile devices with `if (nativeUri != null && !kIsWeb)` - (Try using the [example](https://github.com/WalletConnect/WalletConnectModalFlutter/tree/master/example/sign)).

But if we install this as an PWA - It stops working specially on ios.

**Comment by redDwarf03** [comment]
@gvbinarybard i will try to check https://github.com/WalletConnect/WalletConnectModalFlutter but my need is not with mobile browser. I create a DApp with flutter web and i would like to use with desktop and EVM Wallet extension chrome

**Comment by gvbinarybard** [comment]
@redDwarf03 - Ah I see , I dont think so WalletConnectModal will be able to serve the Wallet extension

**Comment by redDwarf03** [comment]
@gvbinarybard do you know a solution for that please?

**Comment by gvbinarybard** [comment]
@redDwarf03 - Well I haven't tried it but What I can think of ihacky way s to have a react app loaded inside a Flutter webview iframe
Wallet connect react/ Wagmi does support the  Wallet extension

**Comment by gvbinarybard** [comment]
@kaumudpa - Sorry Mate got busy with some  work so forgot to post my solution , here is the [branch](https://github.com/gvbinarybard/WalletConnectModalFlutterWeb/tree/feature/webworking) do let me know if it works for you

**Comment by asmodeoux** [comment]
FYI you can also try using this fork for Web: https://github.com/asmodeoux/Web3ModalFlutter/tree/ptal

```
web3modal_flutter:
    git: 
      url: https://github.com/asmodeoux/Web3ModalFlutter.git
      ref: ptal
```

I made it show the mobile QR code on the Web so you can scan it with your phone and approve the transactions there. Hope it might help the official development as well 👀

**Comment by kaumudpa** [comment]
@quetool Now that walletconnect V2 is fully web supported. Can we expect this plugin to be web supported any time soon?

**Comment by redDwarf03** [comment]
hello @asmodeoux , i'm trying to execute example app in web mode with a project id filled, but i have an error when i launch the webapp
``` 
The following LateError was thrown building MyHomePage(dirty, dependencies: [Web3ModalTheme], state:
_MyHomePageState#4b739):
LateInitializationError: Field '_w3mService' has not been initialized.

**Comment by asmodeoux** [comment]
@redDwarf03 I use it this way and works pretty well:
```
class _SomePageState extends State<SomePage> {
  W3MService? service;

  @override
  void initState() {
    super.initState();
    initW3M();
  }

  Future<void> initW3M() async {
    final w3mService = W3MService(web3App: YOUR_WEB_APP);
    await w3mService.init();
    print('Service initialized: ${w3mService.status}');
    setState(() {
      service = w3mService;
    });
  }

  Future<void> openModal() async {
    try {
      await service?.openModal(context);
    } catch (e, st) {
      print('Failed to open W3Modal: $e');
    }
  }

  // you can call openModal() once service != null
}
```

Basically, you init the service once the page is opened, after that you use the initialized instance

**Comment by redDwarf03** [comment]
Thank you @matteoberla and @asmodeoux . It works with your example. 
I need to go further into integration now.
Note a few old dependencies on http and package_info_plus, but overall it's great.
 
@quetool , is it possible to build a version on pub.dev for web please

**Comment by kaumudpa** [comment]
The @asmodeoux solution works only to generate the QR code - but it does not open the installed wallet for connection request directly which [[WalletConnectModalFlutter] ](https://github.com/WalletConnect/WalletConnectModalFlutter) does Is there something i am missing?

**Comment by quetool** [comment]
> @quetool , is it possible to build a version on pub.dev for web please

Hello guys! I would need to go through the code/changes, make lot of tests, check if anything breaks in other platforms and after that I could think about building a version but there's currently a lot in the bucket list. I assure you Web support is a priority to me (**WalletConnectFlutterV2** is already done, also **WalletConnectModalFlutter** should be done soon enough) but right now is not possible for me to look at this for Web3Modal. Email Wallets is about to go out and there's so many other things to do.

**Comment by kaumudpa** [comment]
@quetool I would like to request you to reconsider resuming work on this - Its becoming critical for multiple web projects out there especially with the latest release of Flutter.

**Comment by quetool** [comment]
Cc @Sam-Newman

**Comment by kaumudpa** [comment]
Can anyone please pick this up? Willing to contribute monetarily for the time someone puts in this.

**Comment by quetool** [comment]
Hello @kaumudpa ! Currently there is no an estimated time for Web3Modal to support Web platforms, and even after we hit the goal of having Web3Modal running smoothly on web we would need to face the fact that most web users interacts with injected wallets, rather than with WalletConnect protocol, and that support that will require a new different effort. 

I'm trying to highlight that is not an easy lift but we are going to do it as soon as we can, we just have currently different priorities to attend.

For the time being: 
- WalletConnectFlutterV2 runs smoothly on web although connection with injected wallets is not supported.
- WalletConnectModalFlutter runs pretty well on web, little work has still to be done but you could try that one instead of Web3Modal, but again, same problem about injected wallets.

If you are focusing just on WalletConnect Protocol then those 2 are your best options, otherwise we have Web3Modal Web for your web's needs.

![Screenshot 2024-05-31 at 12 25 50](https://github.com/WalletConnect/Web3ModalFlutter/assets/14978705/767e4096-c5a6-4695-8944-37c09f24ed43)

**Comment by gvbinarybard** [comment]
> Can anyone please pick this up? Willing to contribute monetarily for the time someone puts in this.

What use case you are looking into it ?

**Comment by gvbinarybard** [comment]
> Can anyone please pick this up? Willing to contribute monetarily for the time someone puts in this.

@kaumudpa - what use case you are looking into it ? does WalletConnectModalFlutter doesnt serve your purpose ?

**Comment by kaumudpa** [comment]
hi @gvbinarybard . WalletConnectModalFlutter is ok but its kind of a hacky workaround and unreliable - Majority of WEB3 Projects out there don't actually use any Native Apps. Nearly 90% of them visit the website and connect wallet. Further amongst these nearly everyone uses mobile browsers to access these web3 apps - This plugin renders the UI correctly for mobile web instances but while trying to connect any wallet it does nothing. 

WalletConnectModalFlutter does connect via deeplink urls but its unreliable and sometimes does not connect specially with Trust Wallet in iOS. Forget the Injected Web3 Part for now I am of a strong opinion that this plugin should atleast support connecting via native deep links or univeral deeplinks of wallets and ofcourse QR aswell .

**Comment by kaumudpa** [comment]
> gvbinarybard

Your this solution was something which was working very well brother, but lately this is also broken - Just considering 2 wallets for now (MetaMask , Trust) and iOS Safari - Every request to metamask opens a new tab when we approve any request and go back to the ios safari we landup at this new blank tab, which we have to manually close and go back to our original tab. And for Trust - Boy oh Boy - 80% of the times we try to connect "Can't find a valid proposal id for topic 1231231-xxxx-xxxxx-xxxxx-xxxx". Try running your Example itself.

Any yes ofcourse any help will be appriciated.

**Comment by kaumudpa** [comment]
> @kaumudpa - Sorry Mate got busy with some work so forgot to post my solution , here is the [branch](https://github.com/gvbinarybard/WalletConnectModalFlutterWeb/tree/feature/webworking) do let me know if it works for you

Your this solution was something which was working very well brother, but lately this is also broken - Just considering 2 wallets for now (MetaMask , Trust) and iOS Safari - Every request to metamask opens a new tab when we approve any request and go back to the ios safari we landup at this new blank tab, which we have to manually close and go back to our original tab. And for Trust - Boy oh Boy - 80% of the times we try to connect "Can't find a valid proposal id for topic 1231231-xxxx-xxxxx-xxxxx-xxxx". Try running your Example itself.

Any yes ofcourse any help will be appriciated.

**Comment by kaumudpa** [comment]
> @kaumudpa - Sorry Mate got busy with some work so forgot to post my solution , here is the [branch](https://github.com/gvbinarybard/WalletConnectModalFlutterWeb/tree/feature/webworking) do let me know if it works for you

@gvbinarybard  Your this solution was something which was working very well brother, but lately this is also broken - Just considering 2 wallets for now (MetaMask , Trust) and iOS Safari - Every request to metamask opens a new tab when we approve any request and go back to the ios safari we landup at this new blank tab, which we have to manually close and go back to our original tab. And for Trust - Boy oh Boy - 80% of the times we try to connect "Can't find a valid proposal id for topic 1231231-xxxx-xxxxx-xxxxx-xxxx". Try running your Example itself.

Any yes ofcourse any help will be appriciated.

**Comment by gvbinarybard** [comment]
@kaumudpa - It been a while I have looked into this , let me check this weekend

**Comment by kaumudpa** [comment]
@gvbinarybard - Will be very helpful. Thanks.

**Comment by kaumudpa** [comment]
@gvbinarybard Hey mate, sent you an email - Also would it be possible for you to build the example with your implementation with --canvaskit flag - `flutter build web --release --web-renderer canvaskit` and host it on firebase hosting or something. Lets try to resolve this.

**Comment by gvbinarybard** [comment]
@kaumudpa  - can you try this - i did some changes - https://6683d72fd7337b30653495c2--dulcet-douhua-3d428d.netlify.app

**Comment by kaumudpa** [comment]
> https://6683d72fd7337b30653495c2--dulcet-douhua-3d428d.netlify.app

Not working!

**Comment by gvbinarybard** [comment]
@kaumudpa  - lets continue over mail pls

**Comment by redDwarf03** [comment]
We are working on flutter web compatibility actually.
The result of our proposals will be here: https://github.com/WalletConnect/Web3ModalFlutter/pull/164

**Comment by kaumudpa** [comment]
@redDwarf03 The community will owe you big one if this actually sails through! All the best. Cant wait.

**Comment by quetool** [comment]
Hello! We are prioritizing performance and reliability over Web support but that doesn't mean we are not going full cross-platform on Flutter. It is just not a priority right now for Web3Modal.

On the other hand, and more interestingly, nothings stops you to use the [Javascript SDK](https://docs.walletconnect.com/appkit/javascript/core/installation) in your Flutter project, it's easy enough, here a simple example project that I just wrote: https://github.com/quetool/web3modal_flutter_web

However, for Flutter platform currently you have available [walletconnect_flutter_v2](https://pub.dev/packages/walletconnect_flutter_v2) (that is full cross-platform) which is the fundamental and core SDK which you can use to create both Dapps and Wallets and then you also have [walletconnect_modal_flutter](https://pub.dev/packages/walletconnect_modal_flutter) which is the protocol-focused modal.

It is true indeed, as @rollchad mentions, that even if these SDKs that I just mentioned runs and compiles on Web platforms they don't interact with injected wallets and that is something we plan to do in the future.

**Comment by quetool** [comment]
> It is true indeed, as @rollchad mentions, that even if these SDKs that I just mentioned runs and compiles on Web platforms they don't interact with injected wallets and that is something we plan to do in the future.
> 

Just to be clear, [AppKit Javascript SDK](https://docs.walletconnect.com/appkit/javascript/core/installation) does interact with injected wallets, of course, I was referring to the Flutter SDKS that runs on web....

**Comment by redDwarf03** [comment]
> Hello! We are prioritizing performance and reliability over Web support but that doesn't mean we are not going full cross-platform on Flutter. It is just not a priority right now for AppKit.
> 
> On the other hand, and more interestingly, as a temporary workaround, nothings stops you to use the [AppKit Javascript SDK](https://docs.walletconnect.com/appkit/javascript/core/installation) in your Flutter project, it's easy enough, here a simple example project that I just wrote: https://github.com/quetool/web3modal_flutter_web
> 
> That being said, for Flutter platform currently you have available [walletconnect_flutter_v2](https://pub.dev/packages/walletconnect_flutter_v2) (that is full cross-platform) which is the fundamental and core SDK which you can use to create both Dapps and Wallets and then you also have [walletconnect_modal_flutter](https://pub.dev/packages/walletconnect_modal_flutter) which is the protocol-focused modal.
> 
> It is true indeed, as @rollchad mentions, that even if these SDKs that I just mentioned runs and compiles on Web platforms they don't interact with injected wallets and that is something we plan to do in the future.
> 
> Will update as soon as I have news...

This is a very interesting approach.
I took the liberty of making a pull request for compatibility with WebAssembly (WASM)

https://github.com/quetool/web3modal_flutter_web/pull/1

**Comment by quetool** [comment]
Hello @redDwarf03! I have merged it but I hope it's clear that this is just a quick example project that I opened on my personal profile to just explain the idea, it's nothing oficial... However, with a bit of love it could work great.

And also, remember that this solution would cover only web platform, for mobile platforms you will need to go with the official approach, so, unless some complex interoperability is made, you will end up having two implementations of the modal.

Again, In the future we are going to explorer this and more ideas to support web platforms properly on AppKit (Web3Modal)

Thanks!

**Comment by redDwarf03** [comment]
Hehe... yes, I know, but we are trying to help you move in the right direction, step by step, even if my proposed change is just a small one

**Comment by redDwarf03** [comment]
New PR proposed https://github.com/quetool/web3modal_flutter_web/pull/2
This PR is the start of the interaction between Wagmi and Flutter web. I don't know if anyone has already implemented this.

https://github.com/user-attachments/assets/c64f3e48-872c-4a1c-9475-a5b5a713b2e2

Next step: try to call approval method from ERC20 contract

**Comment by Chralu** [comment]
Web compatibility requires a lot of debugging. 
After some efforts, I still get a few blocking issues : https://github.com/WalletConnect/Web3ModalFlutter/pull/164

Considering this, @quetool & @redDwarf03 solution seems more straightforward.

**Comment by kaumudpa** [comment]
> New PR proposed [quetool/web3modal_flutter_web#2](https://github.com/quetool/web3modal_flutter_web/pull/2) This PR is the start of the interaction between Wagmi and Flutter web. I don't know if anyone has already implemented this.
> 
>  Enregistrement.de.l.ecran.2024-08-19.a.23.26.30.mov 
> Next step: try to call approval method from ERC20 contract

@redDwarf03 This is a good approach - Your implementation runs seamlessly in desktop envs. Tried the same in mobile (WEB) env's but No Luck. You think we can implement it for mobile (WEB) env's as well?

**Comment by Chralu** [comment]
@kaumudpa We started a package to wrap Wagmi to Dart (Web target only) :  https://github.com/archethic-foundation/wagmi_flutter_web

This is WIP for now. We will probably focus on the few features we need right now. 
Nevertheless, any contribution will be welcome once the RC is released.

**Comment by redDwarf03** [comment]
🙏🏼 To the community:

If you have some idea these 2 issues:
- https://github.com/dart-lang/sdk/issues/56539
- https://github.com/dart-lang/sdk/issues/56537

**Comment by kaumudpa** [comment]
> @kaumudpa We started a package to wrap Wagmi to Dart (Web target only) : https://github.com/archethic-foundation/wagmi_flutter_web
> 
> This is WIP for now. We will probably focus on the few features we need right now. Nevertheless, any contribution will be welcome once the RC is released.

Will contribute few hours every week as soon as you release RC.

hopefully @gvbinarybard will also contribute.

**Comment by redDwarf03** [comment]
i find a solution to solve JSBigint conversion
```
I create this dart class based on dart test classes but i think dart core team should expose a method to manipulate Bigint and JSBigInt

```
import 'dart:js_interop';

@JS()
external JSBigInt bigInt;

@JS('BigInt')
external JSBigInt createBigInt(String value);

extension on JSBigInt {
  @JS('toString')
  external String toStringExternal();
}
```

**Comment by redDwarf03** [comment]
Well... it's complicated... but we hope we'll get there, even if it's a long way.
The repo is here: https://github.com/archethic-foundation/wagmi_flutter_web
Under development. If you want to contribute, don't hesitate to fork the project and suggest PRs
More people will make faster progress.
There are difficulties with the interop between js and dart.

**Comment by kaumudpa** [comment]
@redDwarf03 We have successfully implemented, `getBalance` `readContract ` and currently WIP on `readContracts` - Hoping to submit a PR tomorrow.

**Comment by redDwarf03** [comment]
> @redDwarf03 We have successfully implemented, `getBalance` `readContract ` and currently WIP on `readContracts` - Hoping to submit a PR tomorrow.

With another project or with a fork ?
If it's with wagmi_flutter_web lib, i'm interested to see how you fix the error with getBalance because i don't find why it doesn't work.
Please send me a temporary PR :))))

**Comment by kaumudpa** [comment]
> > @redDwarf03 We have successfully implemented, `getBalance` `readContract ` and currently WIP on `readContracts` - Hoping to submit a PR tomorrow.
> 
> With another project or with a fork ? If it's with wagmi_flutter_web lib, i'm interested to see how you fix the error with getBalance because i don't find why it doesn't work. Please send me a temporary PR :))))

We have forked the project - Sending you a temp PR shortly.

**Comment by kaumudpa** [comment]
@redDwarf03 Found the issue which you might be facing.

`required this.decimal,` should be `required this.decimals,`

we need to use `decimals` instead of `decimal` across the project.

**Comment by redDwarf03** [comment]
Good job from @kaumudpa 
Don't hesitate to pull the last version on main branch.
Keep pushing!!

**Comment by redDwarf03** [comment]
@kaumudpa I forgot. To avoid double work, can you tell me which actions you're going to implement?
I listed the actions and the status in https://github.com/archethic-foundation/wagmi_flutter_web/blob/main/README.md

**Comment by kaumudpa** [comment]
We will be working on - `readContracts`, `getTransactionReceipt` for now, I see you are working on `writeContract` also please update status for `getBalance` from In Progress to Implemented

**Comment by redDwarf03** [comment]
Some news from wagmi_flutter_web lib to use Web3ModalFlutter with flutter_web
Thanks to @kaumudpa and his team for the work!

Here is a status

***Status***

🔴 Not Implemented Yet.\
🟠 Work In Progress.\
✅ Implemented.\
🛠️ Blocking WASM Support. (Needs rework in future.)\
📄 TODO to be managed 


For more details, refer to the [API documentation](https://wagmi.sh/core/api/actions).

| Action Name                    | Status          |
| ------------------------------ | --------------- |
| `call`                         | 🔴               |
| `connect`                      | 🔴               |
| `deployContract`               | 🔴               |
| `disconnect`                   | 🔴               |
| `estimateFeesPerGas`           | 🔴               |
| `estimateGas`                  | ✅ Implemented   |
| `estimateMaxPriorityFeePerGas` | 🔴               |
| `getAccount`                   | ✅ Implemented   |
| `getBalance`                   | ✅ Implemented   |
| `getBlock`                     | ✅ Implemented   |
| `getBlockNumber`               | 🟠 In progress   |
| `getBlockTransactionCount`     | ✅ Implemented   |
| `getBytecode`                  | 🔴               |
| `getChainId`                   | ✅ Implemented   |
| `getChains`                    | 🟠 In progress   |
| `getClient`                    | 🔴               |
| `getConnections`               | 🔴               |
| `getConnectorClient`           | 🔴               |
| `getConnectors`                | 🔴               |
| `getEnsAddress`                | 🔴               |
| `getEnsAvatar`                 | 🔴               |
| `getEnsName`                   | 🔴               |
| `getEnsResolver`               | 🔴               |
| `getEnsText`                   | 🔴               |
| `getFeeHistory`                | 🔴               |
| `getGasPrice`                  | ✅ Implemented   |
| `getProof`                     | 🔴               |
| `getPublicClient`              | 🔴               |
| `getStorageAt`                 | 🔴               |
| `getToken`                     | 🟠 In progress   |
| `getTransaction`               | ✅ Implemented   |
| `getTransactionConfirmations`  | ✅ Implemented   |
| `getTransactionCount`          | ✅ Implemented   |
| `getTransactionReceipt`        | ✅ Implemented   |
| `getWalletClient`              | 🔴               |
| `multicall`                    | 🔴               |
| `prepareTransactionRequest`    | 🔴               |
| `readContract`                 | ✅ Implemented   |
| `readContracts`                | ✅ Implemented 🛠️ |
| `reconnect`                    | 🔴               |
| `sendTransaction`              | ✅ Implemented   |
| `signMessage`                  | ✅ Implemented   |
| `signTypedData`                | 🔴               |
| `simulateContract`             | 🔴               |
| `switchAccount`                | 🔴               |
| `switchChain`                  | 🔴               |
| `verifyMessage`                | 🔴               |
| `verifyTypedData`              | 🔴               |
| `waitForTransactionReceipt`    | 🔴               |
| `watchAccount`                 | 🔴               |
| `watchAsset`                   | 🔴               |
| `watchBlockNumber`             | 🔴               |
| `watchBlocks`                  | 🔴               |
| `watchChainId`                 | ✅ Implemented   |
| `watchClient`                  | 🔴               |
| `watchConnections`             | 🔴               |
| `watchConnectors`              | 🔴               |
| `watchContractEvent`           | 🔴               |
| `watchPendingTransactions`     | 🔴               |
| `watchPublicClient`            | 🔴               |
| `writeContract`                | ✅ Implemented 📄 | 

And the error management is in progress
Don't hesitate to contribute to this lib https://github.com/archethic-foundation/wagmi_flutter_web

**Comment by redDwarf03** [comment]
https://github.com/user-attachments/assets/82306d15-aa33-4d11-8e5d-a9deb1b347e2

Flutter web + wagmi flutter web + wallet connect :)
It's going well

**Comment by redDwarf03** [comment]
wagmi_flutter_web 1.0.0-rc.2 is available
https://pub.dev/packages/wagmi_flutter_web
